GRPC + Diesel => second steps => simple working solution without SSL and auth (with lots todos to fix)

diff --git a/client_search_grpc_soa/docker/Dockerfile-local b/client_search_grpc_soa/docker/Dockerfile-local
--- a/client_search_grpc_soa/docker/Dockerfile-local
+++ b/client_search_grpc_soa/docker/Dockerfile-local
@@ -12,10 +12,14 @@ EXPOSE 80 8080 443 8443 8000 2735 3000
 
 LABEL rust-test-label-03=value-3
 
+
 RUN apt-get -qq update &&                         \
     # apt-get -qq install openssl                 \
     # apt-get -qq install curl &&                 \
+    # apt-get -qq install postgresql-dev &&       \
+    apt-get -qq install libpq5 &&                 \
     apt-get -qq update && apt-get -qq install libssl-dev
+
 
 RUN adduser \
     --disabled-password \
@@ -28,11 +32,14 @@ RUN adduser \
 USER appuser
 
 
-COPY target/debug/mvv_account_soa  ./bin/
-COPY target/debug/health_checker   ./bin/
+COPY target/debug/mvv_client_search_soa  ./bin/
+#COPY target/debug/http_health_checker    ./bin/
+COPY target/debug/health_checker         ./bin/
+COPY thirdparty/grpcurl/grpcurl_1.9.1_linux_x86_64/grpcurl  ./bin/
 
 ENV RUST_BACKTRACE=$RUN_RUST_BACKTRACE
-ENTRYPOINT ["/bin/mvv_account_soa", "arg1", "arg2"]
+ENTRYPOINT ["/bin/mvv_client_search_soa", "arg1", "arg2"]
 
 # good param  --start-interval=2s is unstable ?!
-HEALTHCHECK --start-period=5s --interval=5s --timeout=3s --retries=6 CMD health_checker https://localhost:${SERVER_PORT}/healthcheck || exit 1
+#HEALTHCHECK --start-period=5s --interval=5s --timeout=3s --retries=6 CMD health_checker http://localhost:${SERVER_PORT}/healthcheck || exit 1
+HEALTHCHECK --start-period=5s --interval=5s --timeout=3s --retries=6 CMD grpcurl -d '{ "service": "" }' -plaintext localhost:${SERVER_PORT} grpc_health_v1.Health/Check || exit 1
